Init

diff --git a/arch/x64/emu/Makefile b/arch/x64/emu/Makefile
--- a/arch/x64/emu/Makefile
+++ b/arch/x64/emu/Makefile
@@ -1,50 +1,54 @@
-PROJECT_NAME := xarch-origin-x64
+PROJECT_NAME ?= xarch-origin-x64.
 SRC_DIR := src
 INCLUDE_DIR := include
 BUILD_DIR := build
 
 CXX ?= g++
-CXX_FLAGS ?= -std=c++17 -Wall -Wextra -Wpedantic -MMD -MP
+CXX_FLAGS ?= -std=c++17 -Wall -Wextra -Wpedantic -MMD -MP -fPIC
 LD_FLAGS ?=
 
 RELEASE_FLAGS ?= -O3 -DNDEBUG -static-libstdc++ -static-libgcc
 
-PLATFORM_NAME ?= $(shell uname -s | tr '[:upper:]' '[:lower:]')
-
-ifeq ($(PLATFORM_NAME),Linux)
-    include toolchains/linux.mk
-endif
-
-ifeq ($(PLATFORM_NAME),Darwin)
-    include toolchains/macos.mk
-endif
-
-ifeq ($(PLATFORM_NAME),Windows)
-    include toolchains/windows.mk
-endif
+PLATFORM_NAME ?= linux-x32_64
+include toolchains/$(PLATFORM_NAME).mk
 
 SOURCES := $(wildcard $(SRC_DIR)/*.cpp)
 OBJECTS := $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/$(PLATFORM_NAME)/%.o,$(SOURCES))
--include $(OBJECTS:.o=.d)
+DEPS := $(OBJECTS:.o=.d)
 
-# Default build (debug)
 all: CXX_FLAGS += -g
 all: $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME)
 
-# Release build
 release: CXX_FLAGS += $(RELEASE_FLAGS)
 release: clean $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME)
 
 $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME): $(OBJECTS)
-	@mkdir -p $(BUILD_DIR)/$(PLATFORM_NAME)
+	@mkdir -p $(dir $@)
 	$(CXX) $(CXX_FLAGS) -I$(INCLUDE_DIR) -o $@ $^ $(LD_FLAGS)
 
 $(BUILD_DIR)/$(PLATFORM_NAME)/%.o: $(SRC_DIR)/%.cpp
-	@mkdir -p $(BUILD_DIR)/$(PLATFORM_NAME)
+	@mkdir -p $(dir $@)
 	$(CXX) $(CXX_FLAGS) -I$(INCLUDE_DIR) -c $< -o $@
 
+-include $(DEPS)
+
+test:
+	g++ -shared -fPIC test/main.cpp -o test/arch.so -Iinclude
+	if ./build/linux-x32_64/xwm load ./test/arch.so this may be anything 2>/dev/null; then \
+		echo "All tests ran successfully"; \
+	else \
+		echo "Test failed with exit code $$?"; \
+	fi
+
+
+
 clean:
-	rm -rf $(BUILD_DIR)/$(PLATFORM_NAME)
+	rm -rf $(BUILD_DIR)
 
 run: all
 	./$(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME)
+
+install: release
+	sudo cp $(BUILD_DIR)/$(PLATFORM_NAME)/$(PROJECT_NAME) /usr/local/bin/
+
+.PHONY: all release clean run test
